---
- name: checkout rbenv_repo for selected users
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=yes
    force=yes
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  ignore_errors: yes
  tags:
    - rbenv

- name: create plugins directory for selected users
  file: state=directory path={{ rbenv_root }}/plugins
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  ignore_errors: yes
  tags:
    - rbenv

- name: install plugins for selected users
  git: >
    repo={{ item[1].repo }}
    dest={{ rbenv_root }}/plugins/{{ item[1].name }}
    version={{ item[1].version }}
    accept_hostkey=yes
    force=yes
  with_nested:
    - "{{ rbenv_users }}"
    - "{{ rbenv_plugins }}"
  become: yes
  become_user: "{{ item[0] }}"
  ignore_errors: yes
  tags:
    - rbenv


- name: add rbenv initialization to $HOME
  template: src=rbenv_user.sh.j2 dest=~/.rbenv/bin/rbenv.sh owner={{ item }} group={{ item }} mode=0755
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  when:
    - ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin'
  tags:
    - rbenv

- lineinfile:
    dest: ~/.bashrc
    line: 'source ~/.rbenv/bin/rbenv.sh'
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ rbenv_users }}"
  when:
    - ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin'
  tags:
    - rbenv

- name: set default-gems for select users
  copy: src=default-gems dest={{ rbenv_root }}/default-gems
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  when:
    - default_gems_file is not defined
  ignore_errors: yes
  tags:
    - rbenv

- name: set custom default-gems for select users
  copy: src={{ default_gems_file }} dest={{ rbenv_root }}/default-gems
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  when:
    - default_gems_file is defined
  ignore_errors: yes
  tags:
    - rbenv

- name: create tempfile for gemrc
  shell: mktemp
  register: tempfile
  tags:
    - gemrc

- name: create gemrc
  lineinfile: dest={{ tempfile.stdout }} line={{ item }} create=yes state=present mode=0644
  with_items:
    - "{{ gemrc }}"
  tags:
    - gemrc

- name: set gemrc for select users
  shell: cp {{ tempfile.stdout }} ~{{ item }}/.gemrc && chmod 644 ~{{ item }}/.gemrc && chown {{ item }} ~{{ item }}/.gemrc
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  ignore_errors: yes
  tags:
    - rbenv
  tags:
    - gemrc

- name: Remove tempfile
  file:
    path: "{{ tempfile.stdout }}"
    state: absent
  tags:
    - gemrc

- name: set vars for select users
  copy: src=vars dest={{ rbenv_root }}/vars
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  ignore_errors: yes
  tags:
    - rbenv

- name: check ruby {{ rbenv.ruby_version }} installed for select users
  shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ rbenv_users }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no
  tags:
    - rbenv

- name: install ruby {{ rbenv.ruby_version }} for select users
  shell: $SHELL -lc "rbenv install {{ rbenv.ruby_version }}"
  become: yes
  become_user: "{{ item[1] }}"
  with_together:
    - "{{ ruby_installed.results }}"
    - "{{ rbenv_users }}"
  when:
    - item[0].rc != 0
  ignore_errors: yes
  environment:
    TMPDIR: "{{ rbenv_tmpdir }}"
  tags:
    - rbenv

- name: check if user ruby version is {{ rbenv.ruby_version }}
  shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ rbenv_users }}"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no
  tags:
    - rbenv

- name: set ruby {{ rbenv.ruby_version }} for select users
  shell: $SHELL -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  become: yes
  become_user: "{{ item[1] }}"
  with_together:
    - "{{ ruby_selected.results }}"
    - "{{ rbenv_users }}"
  when:
    - item[0].rc != 0
  ignore_errors: yes
  tags:
    - rbenv
